# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=200)),
                ('image_tags', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=200)),
                ('tag_images', models.TextField()),
            ],
        ),
    ]
